name: Build and Push Docker Image

on:
  push:
    branches: [main]
  schedule:
    - cron: 0 21 * * 6
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN}}
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY}/iptv-org-epg-docker
          DOCKER_TAG=latest
          docker build . -t $IMAGE_NAME:$DOCKER_TAG
          docker push $IMAGE_NAME:$DOCKER_TAG
